# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://cloud.google.com/appengine/docs/standard/python/config/appref

service: echorpc
runtime: python27
threadsafe: true
api_version: 1

# https://cloud.google.com/appengine/docs/standard/python/tools/appstats
builtins:
- appstats: on

handlers:
- url: /echo/static/proxy.html
  static_files: static/proxy.html
  upload: static/proxy.html
  secure: always
- url: /echo/discovery/v1/apis/echo/v1/rest
  static_files: static/echo-v1.discovery
  upload: static/echo-v1.discovery
  mime_type: application/json
  secure: always
- url: /echo/echo/.*
  script: echo.api
  secure: always
- url: /
  static_files: app/index.html
  upload: app/index.html
  secure: always
- url: /*
  static_dir: app
  secure: always

# https://cloud.google.com/appengine/docs/standard/python/tools/built-in-libraries-27
libraries:
- name: protorpc
  version: 1.0
